name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        scipy-version: ['1.11.4', '1.12.0', '1.13.1', '1.14.1', '1.15.3']
        exclude:
          - scipy-version: '1.15.3'
            python-version: '3.9'
          - scipy-version: '1.14.1'
            python-version: '3.9'
          - scipy-version: '1.14.1'
            python-version: '3.13'
          - scipy-version: '1.13.1'
            python-version: '3.13'
          - scipy-version: '1.12.0'
            python-version: '3.13'
          - scipy-version: '1.11.4'
            python-version: '3.13'
    steps:
    - uses: actions/checkout@v4
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install scipy==${{ matrix.scipy-version }}
        python -m pip install pytest
    - name: Install odeintw
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        python -m pytest
