name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        scipy-version: ['1.7.3', '1.8.1', '1.9.3', '1.10.1', '1.11.2']
        exclude:
          - scipy-version: '1.11.1'
            python-version: '3.8'
          - scipy-version: '1.9.3'
            python-version: '3.11'
          - scipy-version: '1.8.1'
            python-version: '3.11'
          - scipy-version: '1.7.3'
            python-version: '3.10'
          - scipy-version: '1.7.3'
            python-version: '3.11'

    steps:
    - uses: actions/checkout@v4
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install scipy==${{ matrix.scipy-version }}
        python -m pip install pytest
    - name: Install odeintw
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        python -m pytest
